---
- name: "Generate Sing-Box secrets"
  ansible.builtin.command:
    cmd: "docker run --rm ghcr.io/sagernet/sing-box:latest {{ item }}"
  loop:
    - "generate reality-keypair"
    - "generate rand 8 --hex"
    - "generate uuid"
  register: bifrost_gen_secrets
  changed_when: false

- name: "Display Sing-Box secrets"
  ansible.builtin.debug:
    msg: "{{ item.stdout_lines }}"
  loop: "{{ bifrost_gen_secrets.results }}"
  loop_control:
    label: "{{ item.item }}"
