---
- name: Render Bifrost server sing-box config
  ansible.builtin.template:
    src: "server/config.json.j2"
    dest: "{{ bifrost_root }}/sing-box/config.json"
    mode: "0644"

- name: Render Bifrost server compose config
  ansible.builtin.template:
    src: "server/compose.yml.j2"
    dest: "{{ bifrost_root }}/compose.yml"
    mode: "0644"
